name: Deploy Website via FTP

on:
  push:
    branches:
      - main # Change this if your default branch is 'master'

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ./htdocs/
